apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      imagePullSecrets:
      - name: docker-login-secret
      containers:
      - name: streamlit-app
        image: csye712504/streamlit:latest
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://pinecone-app.webapp.svc.cluster.local:8000"
        command: ["streamlit"]
        args: ["run", "app.py", "--server.baseUrlPath=dashboard", "--server.enableCORS=false"]

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: webapp
  labels:
    app: streamlit-app
spec:
  selector:
    app: streamlit-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8501
  type: ClusterIP

